name: iptv_player
description: A multiplatform IPTV player for Android, iOS, Windows, macOS, Linux, and web with M3U playlist support.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.9.0-0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^2.0.1
  http: ^1.5.0
  wakelock_plus: ^1.6.1
  web: ^1.1.1
  xml: ^6.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
