name: iptv_player
description: A Flutter IPTV player for Android, Windows, and Linux with M3U playlist support.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.9.0-0

dependencies:
  flutter:
    sdk: flutter
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
